---
title: "STAT 5550 project"
author: "James Laughead"
date: "4/13/2022"
output: html_document
---

```{r}
project.data <- read.csv("IPG2211A2N.csv")
df <- (project.data$IPG2211A2N)
df <- df[433:998]

df.ts = ts(df, frequency = 12, start=c(1975, 1))
plot.ts(df.ts, xlab = "Year", ylab = "Gas/Electric production output level", main = "USA ultility production output levels, Jan 1975 - Feb 2022")
acf(df, lag.max = 100, main = "ACF plot of Gas/Electric production output level data")


t = 1:length(df)
c = cos(2*pi*t/12)
s = sin(2*pi*t/12)
mod3 = lm(df.ts ~ t+c+s)
summary(mod3)


plot(t, df.ts, main = "Estimated trend and seasonal component", xlab = "Months since Jan 1975", ylab = "Gas/Electric production output level" )
lines(mod3$fit)

a <- summary(mod3)$coefficients
ut0 <- a[ 1,1 ]
ut1 <- a[ 2,1 ]
uc1 <- a[ 3,1 ]
uc2 <- a[ 4,1 ]



plot(time(df), ut0 + (ut1*t), type="l", col="pink2", lwd=2,
 main="Estimated Trend", xlab = "Months since Jan 1975", ylab = "Gas/Electric production output level" )


plot(time(df), (2.990434*(c) +  0.77011133*(s)), type="l", col="pink2", lwd=2,
 main="Estimated Seasonal Component", xlab = "Months since Jan 1975", ylab = "Gas/Electric production output level" )
abline(h=0, lty=3)


# Make a time series object with the detrended, deseasonalized data:
detrended = df - (ut0 + ut1*t) - ((2.9904347*(c))+((0.77011133)*(s)))
detrended = ts(detrended, frequency = 12, start=c(1975, 1))

plot.ts(detrended, ylab="", main="Detrended, Deseasonalized Data of Gas/Electric production output",xlab = "Year")
acf(detrended, lag.max = 100)




varve.arma = arima(detrended, order = c(1, 0, 1))
varve.arma   
tsdiag(varve.arma, gof.lag=20)


varve.arma = arima(detrended, order = c(0, 0, 1))
varve.arma   
tsdiag(varve.arma, gof.lag=10)


varve.arma = arima(detrended, order = c(7, 0, 12))
varve.arma   
tsdiag(varve.arma, gof.lag=10)

varve.arma = arima(detrended, order = c(6, 0, 11))
varve.arma   
tsdiag(varve.arma, gof.lag=10)

varve.arma = arima(detrended, order = c(7, 0, 13))
varve.arma   
tsdiag(varve.arma, gof.lag=10)

arima(detrended, order = c(1, 0, 1))


a22 <- arima(detrended, order = c(7, 0, 13))
library(astsa)

plot(density(a22$residuals), main = "density of Residuals for ARMA(7,13)")


mod4 = sarima(df, 7,0,13, no.constant=T, details=F)

mod4a = arima(df, order=c(7,0,13), include.mean=F)


mod4.pr = predict(mod4a, n.ahead=2)

PI.nov = c(mod4.pr$pr[1] - 2*mod4.pr$se[1], mod4.pr$pr[1] + 2*mod4.pr$se[1])
PI.dec = c(mod4.pr$pr[2] - 2*mod4.pr$se[2], mod4.pr$pr[2] + 2*mod4.pr$se[2])



mod4.pr = predict(mod4a, n.ahead=45, interval = "pred")

zhat = mod4.pr$pr
pi.z.upper = mod4.pr$pr + 2*mod4.pr$se
pi.z.lower = mod4.pr$pr - 2*mod4.pr$se


plot(df, ylab="Residuals", main=expression("Forecasting of USA utility output"))
points(mod4.pr$pred, col="red")
lines(pi.z.upper, lty=2, col="blue")
lines(pi.z.lower, lty=2, col="green")

```


```{r}


mod4a2 <- sarima(df, 1, 1, 1, P = 0, D = 1, Q = 1, S = 12)
mod4a3 <- sarima(df, 1, 2, 1, P = 0, D = 1, Q = 1, S = 12)
mod4a4 <- sarima(df, 1, 1, 1, P = 1, D = 1, Q = 1, S = 12)
mod4a5 <- sarima(df, 1, 2, 1, P = 1, D = 2, Q = 1, S = 12)
mod4a6 <- sarima(df, 2, 1, 2, P = 1, D = 1, Q = 1, S = 12)

mod4a2$AIC
mod4a3$AIC
mod4a4$AIC
mod4a5$AIC
mod4a6$AIC

mod4a <- sarima.for(df,n.ahead = 45,1,1,1,P=0,D=1,Q=1,S=12, main = "USA utility production output forecast")

#mod4.pr = predict(mod4a, n.ahead=45, interval = "pred")

mod4.pr = mod4a



PI.nov = c(mod4.pr$pr[1] - 2*mod4.pr$se[1], mod4.pr$pr[1] + 2*mod4.pr$se[1])
PI.dec = c(mod4.pr$pr[2] - 2*mod4.pr$se[2], mod4.pr$pr[2] + 2*mod4.pr$se[2])


zhat = mod4.pr$pr
pi.z.upper = mod4.pr$pr + 2*mod4.pr$se
pi.z.lower = mod4.pr$pr - 2*mod4.pr$se


plot(df, ylab="Residuals", main=expression("Forecasting of USA utility output"))
points(mod4.pr$pred, col="brown")
lines(pi.z.upper, lty=2, col="blue")
lines(pi.z.lower, lty=2, col="orange")


```





